org: bonizario
service: foodiary-api

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  environment: ${file(./serverless/config/env.yml)}

package:
  individually: true

custom:
  cognito:
    UserPoolName: ${self:service}-${self:provider.stage}-user-pool
    UserPoolClientName: ${self:service}-${self:provider.stage}-user-pool-client

build:
  esbuild:
    configFile: ./esbuild.config.mjs

functions:
  - ${file(./serverless/functions/auth.yml)}

resources:
  - ${file(./serverless/resources/user-pool.yml)}
