org: bonizario
service: foodiary-api

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  environment: ${file(./serverless/config/env.yml)}
  iam:
    role: ${file(./serverless/config/role.yml)}
  httpApi:
    disableDefaultEndpoint: ${env:DISABLE_DEFAULT_APIGW_ENDPOINT, false}
    authorizers:
      CognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt UserPool.ProviderURL
        audience:
          - !Ref UserPoolClient

package:
  individually: true

custom:
  cognito:
    UserPoolName: ${self:service}-${self:provider.stage}-user-pool
    UserPoolClientName: ${self:service}-${self:provider.stage}-user-pool-client

build:
  esbuild:
    configFile: ./esbuild.config.mjs

functions:
  - ${file(./serverless/functions/auth.yml)}
  - ${file(./serverless/functions/meals.yml)}

resources:
  - ${file(./serverless/resources/user-pool.yml)}
  - ${file(./serverless/resources/main-table.yml)}
  - ${file(./serverless/resources/api-gw-custom-domain.yml)}
