statements:
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:GetItem
      - dynamodb:PutItem
    Resource:
      - !GetAtt MainTable.Arn
      - !Sub "${MainTable.Arn}/index/*"

  - Effect: Allow
    Action: cognito-idp:AdminDeleteUser
    Resource: !GetAtt UserPool.Arn

  - Effect: Allow
    Action: s3:PutObject
    Resource: !Sub "${MealsBucket.Arn}/*"
